# Configuration for Snakemake Workflow

# Paths
data_dir: "data"
results_dir: "results"
scripts_dir: "workflow/scripts"

# Parameters for specific rules or scripts
parameters:
  threshold: 100  # Example threshold used in scripts or rules


# Output files
output_files:
  count_null_data: "{results_dir}/count_null_data.txt"
  final_report: "{results_dir}/report.pdf"

# Any other configuration that might be needed
